
package com.mycompany.celestepharmacy;

import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ssstepbro
 */
public class SalesPage extends javax.swing.JFrame {
    
    //variables
     private Date date = null;
    private  ArrayList<Sales> sData = new ArrayList<>();
    private  int id = 0;
    private int sid = 0;
    private double totalE = 0.0;

    /**
     * Creates new form SalesPage
     */
    public SalesPage() throws SQLException {
        initComponents();
        sData = ConH2.getSData();
        //                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //add array to table expTb
                     
                     for(Sales i : sData){
                         if(i.getSid()<= id){
                             
                         }else{
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             id = i.getSid();
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTb = new javax.swing.JTable();
        viagra = new javax.swing.JToggleButton();
        morning = new javax.swing.JToggleButton();
        control = new javax.swing.JToggleButton();
        yest = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        totalExp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("SALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        salesTb.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        salesTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ITEM", "AMOUNT", "COST", "DEPARTMENT", "DATE"
            }
        ));
        jScrollPane1.setViewportView(salesTb);

        viagra.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        viagra.setText("VIAGRA");
        viagra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viagraActionPerformed(evt);
            }
        });

        morning.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        morning.setText("MORNING AFTER");
        morning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningActionPerformed(evt);
            }
        });

        control.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        control.setText("CONTROL L");
        control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlActionPerformed(evt);
            }
        });

        yest.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        yest.setText("YESTERDAY");
        yest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viagra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(morning, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(control, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(yest, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viagra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morning, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(control, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("TOTAL");

        totalExp.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        totalExp.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(totalExp)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(totalExp))
                    .addComponent(jButton4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             this.dispose();
        HomePage page = new HomePage();
         page.setLocationRelativeTo(null);
        page.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void viagraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viagraActionPerformed
              toggleState();
    }//GEN-LAST:event_viagraActionPerformed

    private void morningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningActionPerformed
              toggleState();
    }//GEN-LAST:event_morningActionPerformed

    private void controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlActionPerformed
       toggleState();
    }//GEN-LAST:event_controlActionPerformed

    private void yestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yestActionPerformed
        toggleState();
    }//GEN-LAST:event_yestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new SalesPage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SalesPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private  void toggleState(){
        if(!viagra.isSelected() && !morning.isSelected() && !control.isSelected() && !yest.isSelected() ){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                            
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
    }
        if(viagra.isSelected() && !morning.isSelected() && !control.isSelected() && !yest.isSelected()){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(date))){
                                  if(i.getDepartment().equals("Viagras")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
    }
        if(!viagra.isSelected() && morning.isSelected() && !control.isSelected() && !yest.isSelected()){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(date))){
                                  if(i.getDepartment().equals("Morning After")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
        if(!viagra.isSelected() && !morning.isSelected() && control.isSelected() && !yest.isSelected()){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(date))){
                                  if(i.getDepartment().equals("Control")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
        if(!viagra.isSelected() && !morning.isSelected() && !control.isSelected() && yest.isSelected() ){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   Date yest = getYest(date);
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(yest))){
                                
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                            
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
         if(viagra.isSelected() && !morning.isSelected() && !control.isSelected() && yest.isSelected() ){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   Date yest = getYest(date);
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(yest))){
                             if(i.getDepartment().equals("Viagras")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
         
         if(!viagra.isSelected() && morning.isSelected() && !control.isSelected() && yest.isSelected() ){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   Date yest = getYest(date);
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(yest))){
                             if(i.getDepartment().equals("Morning After")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
         
         if(!viagra.isSelected() && !morning.isSelected() && control.isSelected() && yest.isSelected() ){
             try {
                   long now = System.currentTimeMillis();

                   date = new Date(now);
                   Date yest = getYest(date);
                  sid = 0;
                  //array of data into expTbid
                    sData = ConH2.getSData();
//                    System.out.println(eData.get(0).toTable());
                     DefaultTableModel tbl = (DefaultTableModel)salesTb.getModel();
                     //delete entries
                     tbl.setRowCount(0);
                     totalE = 0;
                     //add array to table expTb
                     for(Sales i : sData ){
                         if(i.getSid()<= sid){
                             
                         }else{
                             if(String.valueOf(i.getDate()).equals(String.valueOf(yest))){
                             if(i.getDepartment().equals("Control")){
                             tbl.addRow(i.toTable());
                             totalE += i.getCost();
                             sid = i.getSid();
                             }
                             }
                            
                             
                         }
                         
                     }
                     totalExp.setText(String.valueOf(totalE));
                     
                     
                } catch (SQLException ex) {
                    Logger.getLogger(ExpensesPage.class.getName()).log(Level.SEVERE, null, ex);
                }    
        }
    }
    
    private Date getYest (Date tod){
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(tod);
        calendar.add(Calendar.DATE, -1);
        return new Date(calendar.getTimeInMillis());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton control;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton morning;
    private javax.swing.JTable salesTb;
    private javax.swing.JLabel totalExp;
    private javax.swing.JToggleButton viagra;
    private javax.swing.JToggleButton yest;
    // End of variables declaration//GEN-END:variables
}
